FROM --platform=linux/amd64 ubuntu:latest
RUN apt-get update && \
        apt-get install -y python3 python3-pip libpq-dev libcurl4-openssl-dev libssl-dev && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

# Stage 2: Install pipenv and dependencies
RUN pip3 install pipenv
WORKDIR /app
COPY Pipfile Pipfile.lock ./
COPY . .

RUN pipenv install --system --deploy

# for debugging purposes (keeping the docker open)
# ENTRYPOINT ["tail", "-F", "anything"]

CMD ["pipenv", "--python", "/usr/bin/python3", "run", "watchmedo", "auto-restart", "--directory", "server", "--recursive", "--pattern", "*.py", "--", "pipenv", "run", "celery", "--app", "server.tasks.generate", "worker", "--pool=eventlet", "--concurrency=50", "--loglevel=info"]
